# Generated by Django 4.1.1 on 2022-11-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_group_name', models.CharField(max_length=100)),
                ('agent_group_priority', models.IntegerField()),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('datetime_change', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_type', models.IntegerField()),
                ('agent_group', models.IntegerField()),
                ('agent_status', models.IntegerField()),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('datetime_change', models.DateTimeField(auto_now_add=True)),
                ('agentGroups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.agentgroups')),
                ('agentTypes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.agenttypes')),
            ],
        ),
        migrations.CreateModel(
            name='AgentCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_x', models.IntegerField()),
                ('coordinate_y', models.IntegerField()),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.agents')),
            ],
        ),
    ]
