# Generated by Django 4.1.1 on 2022-11-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentcoordinates',
            old_name='agent',
            new_name='agent_id',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='agentGroups',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='agentTypes',
        ),
        migrations.AlterField(
            model_name='agents',
            name='agent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.agentgroups'),
        ),
        migrations.AlterField(
            model_name='agents',
            name='agent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.agenttypes'),
        ),
    ]
