# Generated by Django 4.1.1 on 2022-09-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_file', models.IntegerField()),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('check_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_file', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('path_file', models.TextField(blank=True, max_length=300)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('id_file_foreign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interface.fileslogs')),
            ],
        ),
    ]
