# Generated by Django 4.1.1 on 2023-04-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_step', models.IntegerField(blank=True, null=True)),
                ('agent_error_value', models.FloatField(blank=True, null=True)),
                ('datetime_create', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_agent_errors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentErrorsView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('agent_step', models.IntegerField(blank=True, null=True)),
                ('agent_error_value', models.FloatField(blank=True, null=True)),
                ('datetime_create', models.DateTimeField(blank=True, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'v_agent_errors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=250, null=True)),
                ('file_type', models.CharField(blank=True, max_length=250, null=True)),
                ('file_path', models.CharField(blank=True, max_length=250, null=True)),
                ('file_description', models.CharField(blank=True, max_length=250, null=True)),
                ('create_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_agent_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_group_name', models.CharField(max_length=100)),
                ('agent_group_priority', models.IntegerField()),
                ('datetime_create', models.DateTimeField()),
                ('datetime_change', models.DateTimeField()),
                ('agent_group_description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 't_agent_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, max_length=250, null=True)),
                ('agent_status', models.IntegerField(blank=True, null=True)),
                ('agent_description', models.CharField(blank=True, max_length=250, null=True)),
                ('datetime_create', models.DateTimeField(blank=True, null=True)),
                ('datetime_change', models.DateTimeField(blank=True, null=True)),
                ('agent_port', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_agents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentsView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(blank=True, max_length=250, null=True)),
                ('agent_group_name', models.CharField(max_length=100)),
                ('agent_status', models.IntegerField(blank=True, null=True)),
                ('agent_description', models.CharField(blank=True, max_length=250, null=True)),
                ('datetime_create', models.DateTimeField(blank=True, null=True)),
                ('datetime_change', models.DateTimeField(blank=True, null=True)),
                ('agent_type', models.CharField(max_length=100)),
                ('agent_port', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_agents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(max_length=100)),
                ('agent_type_description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 't_agent_types',
                'managed': False,
            },
        ),
    ]
