# Generated by Django 4.1.1 on 2023-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentNeuralNetworkState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neural_network_state', models.CharField(blank=True, max_length=1000000, null=True)),
                ('file_description', models.CharField(blank=True, max_length=250, null=True)),
                ('create_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_agent_neural_network_state',
                'managed': False,
            },
        ),
    ]
