# Generated by Django 4.1.1 on 2022-12-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_rename_agent_agentcoordinates_agent_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentcoordinates',
            old_name='agent_id',
            new_name='agent_port',
        ),
        migrations.AddField(
            model_name='agents',
            name='agent_port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
